# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

# Flutter build
variables:
  projectDirectory: plus0ne_flutter

jobs:
  - job: BuildFlutter
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - task: FlutterInstall@0
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(projectDirectory)
